server:
  port: 8080

spring:
  profiles:
      active: local
  application:
    name: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/newt?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #配置监控系统拦截的filters，去掉后面监控界面sql将无法统计，‘wall’用于防火墙
    filers: stat,wall,log4j2
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PACache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
druid:
  allow: 127.0.0.1
  deny: xxx
  loginUsername: zhangchaochao
  loginPassword: zhangchaochao
  resetEnable: false
mybatis:
  mapper-locations: **/com/newt/mapper/*.xml
  #schema:
  #  - classpath:sql/department.sql
  #  - classpath:sql/employee.sql
  #initialization-mode: always

---


server:
  port: 8080

spring:
  profiles: local
  application:
    name: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/newt?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #配置监控系统拦截的filters，去掉后面监控界面sql将无法统计，‘wall’用于防火墙
    filers: stat,wall,log4j2
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PACache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
druid:
  allow: 127.0.0.1
  deny: xxx
  loginUsername: zhangchaochao
  loginPassword: zhangchaochao
  resetEnable: false
mybatis:
  mapper-locations: **/com/newt/mapper/*.xml
    #schema:
    #  - classpath:sql/department.sql
    #  - classpath:sql/employee.sql
    #initialization-mode: always