server:
  port: 8080
spring:
  profiles:
      active: local
  application:
    name: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/newt?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #配置监控系统拦截的filters，去掉后面监控界面sql将无法统计，‘wall’用于防火墙
    filers: stat,wall,log4j2
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PACache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
druid:
  allow: 127.0.0.1
  deny: xxx
  loginUsername: zhangchaochao
  loginPassword: zhangchaochao
  resetEnable: false
mybatis:
  mapper-locations: classpath:com/newt/mapper/**/*.xml
  #schema:
  #  - classpath:sql/department.sql
  #  - classpath:sql/employee.sql
  #initialization-mode: always

---


server:
  port: 8080
spring:
  profiles: local
  application:
    name: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/newt?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #配置监控系统拦截的filters，去掉后面监控界面sql将无法统计，‘wall’用于防火墙
    filers: stat,wall,log4j2
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PACache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
druid:
  allow: 127.0.0.1
  deny: xxx
  loginUsername: zhangchaochao
  loginPassword: zhangchaochao
  resetEnable: false
mybatis:
  mapper-locations: classpath:com/newt/mapper/**/*.xml
redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 20
    min-idle: 1
    max-active: 20
    max-wait: 60000
  database: 0 #默认是索引为0的数据库
oss:
  type: 1 # 1:阿里云，2：七牛，3：腾讯云
  aliyun:
    first:
      accessKeyId: LTAIqDT9s8bSbJHi # 授权ID
      accessKeySecret: fuPIueM0IkW52b3s8LNHZOhXyjnM2U # 授权秘钥
      bucketName:  newt# 指定桶名
      endPoint: oss-cn-beijing.aliyuncs.com # 访问域名，也指文件存储在哪个区域节点，如华北1
      styleName:   # 指定访问文件样式，可对图片精选模糊压缩等改变<非必传项>。此值同样是在阿里云设置的
      prefix: admin
    second:
      accessKeyId: LTAIqDT9s8bSbJHi
      accessKeySecret: fuPIueM0IkW52b3s8LNHZOhXyjnM2U
      bucketName: newt
      endPoint: oss-cn-beijing.aliyuncs.com
      styleName:
      prefix: user
    domain: http://www.newt.fun
    defalut:
      accessKeyId: LTAIqDT9s8bSbJHi
      accessKeySecret: fuPIueM0IkW52b3s8LNHZOhXyjnM2U
      bucketName: newt
      endPoint: oss-cn-beijing.aliyuncs.com
      styleName:
      prefix: default
user:
  defaultPwd: 000000
  favicon: http://www.newt.fun/favicon.ico
  userIcon: http://www.newt.fun/favicon.ico